// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/justmart/backend/internal/service/analytics"
	"github.com/justmart/backend/internal/service/auth"
	"github.com/justmart/backend/internal/service/backup"
	"github.com/justmart/backend/internal/service/batch"
	"github.com/justmart/backend/internal/service/branch"
	"github.com/justmart/backend/internal/service/customer"
	"github.com/justmart/backend/internal/service/health"
	"github.com/justmart/backend/internal/service/prescription"
	"github.com/justmart/backend/internal/service/priceagreement"
	"github.com/justmart/backend/internal/service/productdiscount"
	"github.com/justmart/backend/internal/service/productpricetier"
	"github.com/justmart/backend/internal/service/purchasing"
	"github.com/justmart/backend/internal/service/stock"
	"github.com/justmart/backend/internal/service/stocktake"
	"github.com/justmart/backend/internal/service/supplier"
	"github.com/justmart/backend/internal/service/transfer"
	"github.com/justmart/backend/internal/service/unit"
	"github.com/justmart/backend/internal/service/user"
	"github.com/justmart/backend/internal/service/warehouse"
)

import (
	_ "github.com/glebarez/go-sqlite"
	_ "github.com/jackc/pgx/v5/stdlib"
	_ "time/tzdata"
)

// Injectors from wire.go:

// initApp builds the whole server object graph: config -> DB (migrated) ->
// auth primitives -> every ConnectRPC service -> the HTTP stack. The returned
// cleanup closes the DB pool.
func initApp(path configPath, version2 buildVersion) (*App, func(), error) {
	config, err := provideConfig(path)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := provideDB(config)
	if err != nil {
		return nil, nil, err
	}
	userService := user.NewUserService(db)
	analyticsService := analytics.NewAnalyticsService(db)
	issuer := provideIssuer(config)
	refreshIssuer := provideRefreshIssuer(config, db)
	loginLimiter := provideLoginLimiter()
	authService := auth.NewAuthService(db, issuer, refreshIssuer, loginLimiter)
	backups := backup.NewBackupService(db, config)
	batchService := batch.NewBatchService(db)
	branchService := branch.NewBranchService(db)
	connectorService := provideConnectorService(config)
	customerService := customer.NewCustomerService(db)
	healthService := health.NewHealthService(db)
	priceAgreementService := priceagreement.NewPriceAgreementService(db)
	prescriptionService := prescription.NewPrescriptionService(db)
	productDiscountService := productdiscount.NewProductDiscountService(db)
	productPriceTierService := productpricetier.NewProductPriceTierService(db)
	productService := provideProductService(db, config, connectorService)
	purchaseOrders := purchasing.NewPurchaseOrderService(db)
	purchasePayments := purchasing.NewPurchasePaymentService(db)
	purchaseReceipts := purchasing.NewPurchaseReceiptService(db)
	purchaseReturns := purchasing.NewPurchaseReturnService(db)
	saleService := provideSaleService(db, config, connectorService)
	mainTunnelToken := provideTunnelToken(config, db)
	settingsService := provideSettingsService(db, config, version2, mainTunnelToken)
	stockService := stock.NewStockService(db)
	stocktakeService := stocktake.NewStocktakeService(db)
	supplierService := supplier.NewSupplierService(db)
	transferService := transfer.NewTransferService(db)
	unitService := unit.NewUnitService(db)
	warehouseService := warehouse.NewWarehouseService(db)
	handlers := Handlers{
		Analytics:         analyticsService,
		Auth:              authService,
		Backups:           backups,
		Batches:           batchService,
		Branches:          branchService,
		Connectors:        connectorService,
		Customers:         customerService,
		Health:            healthService,
		PriceAgreements:   priceAgreementService,
		Prescriptions:     prescriptionService,
		ProductDiscounts:  productDiscountService,
		ProductPriceTiers: productPriceTierService,
		Products:          productService,
		PurchaseOrders:    purchaseOrders,
		PurchasePayments:  purchasePayments,
		PurchaseReceipts:  purchaseReceipts,
		PurchaseReturns:   purchaseReturns,
		Sales:             saleService,
		Settings:          settingsService,
		Stock:             stockService,
		Stocktakes:        stocktakeService,
		Suppliers:         supplierService,
		Transfers:         transferService,
		Units:             unitService,
		Users:             userService,
		Warehouses:        warehouseService,
	}
	v := provideAuthPolicy()
	handlerOption := provideInterceptors(issuer, v, db)
	handler := provideRootHandler(handlers, handlerOption)
	server := provideHTTPServer(config, handler)
	tunnelRunner := provideTunnelRunner(mainTunnelToken)
	app := &App{
		Cfg:    config,
		DB:     db,
		Users:  userService,
		Server: server,
		Tunnel: tunnelRunner,
	}
	return app, func() {
		cleanup()
	}, nil
}
