// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: event_iface/v1/service.proto

package event_ifacev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/wargasipil/warga_collections/definitions/event_iface/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EventServiceName is the fully-qualified name of the EventService service.
	EventServiceName = "event_iface.v1.EventService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EventServicePullProcedure is the fully-qualified name of the EventService's Pull RPC.
	EventServicePullProcedure = "/event_iface.v1.EventService/Pull"
	// EventServiceSendProcedure is the fully-qualified name of the EventService's Send RPC.
	EventServiceSendProcedure = "/event_iface.v1.EventService/Send"
	// EventServiceAckProcedure is the fully-qualified name of the EventService's Ack RPC.
	EventServiceAckProcedure = "/event_iface.v1.EventService/Ack"
	// EventServiceTopicListProcedure is the fully-qualified name of the EventService's TopicList RPC.
	EventServiceTopicListProcedure = "/event_iface.v1.EventService/TopicList"
	// EventServiceSubscriptionListProcedure is the fully-qualified name of the EventService's
	// SubscriptionList RPC.
	EventServiceSubscriptionListProcedure = "/event_iface.v1.EventService/SubscriptionList"
	// EventServiceMaintainProcedure is the fully-qualified name of the EventService's Maintain RPC.
	EventServiceMaintainProcedure = "/event_iface.v1.EventService/Maintain"
)

// EventServiceClient is a client for the event_iface.v1.EventService service.
type EventServiceClient interface {
	Pull(context.Context, *connect.Request[v1.PullRequest]) (*connect.ServerStreamForClient[v1.PullResponse], error)
	Send(context.Context, *connect.Request[v1.SendRequest]) (*connect.Response[v1.SendResponse], error)
	Ack(context.Context, *connect.Request[v1.AckRequest]) (*connect.Response[v1.AckResponse], error)
	TopicList(context.Context, *connect.Request[v1.TopicListRequest]) (*connect.Response[v1.TopicListResponse], error)
	SubscriptionList(context.Context, *connect.Request[v1.SubscriptionListRequest]) (*connect.Response[v1.SubscriptionListResponse], error)
	Maintain(context.Context, *connect.Request[v1.MaintainRequest]) (*connect.ServerStreamForClient[v1.MaintainResponse], error)
}

// NewEventServiceClient constructs a client for the event_iface.v1.EventService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEventServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EventServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	eventServiceMethods := v1.File_event_iface_v1_service_proto.Services().ByName("EventService").Methods()
	return &eventServiceClient{
		pull: connect.NewClient[v1.PullRequest, v1.PullResponse](
			httpClient,
			baseURL+EventServicePullProcedure,
			connect.WithSchema(eventServiceMethods.ByName("Pull")),
			connect.WithClientOptions(opts...),
		),
		send: connect.NewClient[v1.SendRequest, v1.SendResponse](
			httpClient,
			baseURL+EventServiceSendProcedure,
			connect.WithSchema(eventServiceMethods.ByName("Send")),
			connect.WithClientOptions(opts...),
		),
		ack: connect.NewClient[v1.AckRequest, v1.AckResponse](
			httpClient,
			baseURL+EventServiceAckProcedure,
			connect.WithSchema(eventServiceMethods.ByName("Ack")),
			connect.WithClientOptions(opts...),
		),
		topicList: connect.NewClient[v1.TopicListRequest, v1.TopicListResponse](
			httpClient,
			baseURL+EventServiceTopicListProcedure,
			connect.WithSchema(eventServiceMethods.ByName("TopicList")),
			connect.WithClientOptions(opts...),
		),
		subscriptionList: connect.NewClient[v1.SubscriptionListRequest, v1.SubscriptionListResponse](
			httpClient,
			baseURL+EventServiceSubscriptionListProcedure,
			connect.WithSchema(eventServiceMethods.ByName("SubscriptionList")),
			connect.WithClientOptions(opts...),
		),
		maintain: connect.NewClient[v1.MaintainRequest, v1.MaintainResponse](
			httpClient,
			baseURL+EventServiceMaintainProcedure,
			connect.WithSchema(eventServiceMethods.ByName("Maintain")),
			connect.WithClientOptions(opts...),
		),
	}
}

// eventServiceClient implements EventServiceClient.
type eventServiceClient struct {
	pull             *connect.Client[v1.PullRequest, v1.PullResponse]
	send             *connect.Client[v1.SendRequest, v1.SendResponse]
	ack              *connect.Client[v1.AckRequest, v1.AckResponse]
	topicList        *connect.Client[v1.TopicListRequest, v1.TopicListResponse]
	subscriptionList *connect.Client[v1.SubscriptionListRequest, v1.SubscriptionListResponse]
	maintain         *connect.Client[v1.MaintainRequest, v1.MaintainResponse]
}

// Pull calls event_iface.v1.EventService.Pull.
func (c *eventServiceClient) Pull(ctx context.Context, req *connect.Request[v1.PullRequest]) (*connect.ServerStreamForClient[v1.PullResponse], error) {
	return c.pull.CallServerStream(ctx, req)
}

// Send calls event_iface.v1.EventService.Send.
func (c *eventServiceClient) Send(ctx context.Context, req *connect.Request[v1.SendRequest]) (*connect.Response[v1.SendResponse], error) {
	return c.send.CallUnary(ctx, req)
}

// Ack calls event_iface.v1.EventService.Ack.
func (c *eventServiceClient) Ack(ctx context.Context, req *connect.Request[v1.AckRequest]) (*connect.Response[v1.AckResponse], error) {
	return c.ack.CallUnary(ctx, req)
}

// TopicList calls event_iface.v1.EventService.TopicList.
func (c *eventServiceClient) TopicList(ctx context.Context, req *connect.Request[v1.TopicListRequest]) (*connect.Response[v1.TopicListResponse], error) {
	return c.topicList.CallUnary(ctx, req)
}

// SubscriptionList calls event_iface.v1.EventService.SubscriptionList.
func (c *eventServiceClient) SubscriptionList(ctx context.Context, req *connect.Request[v1.SubscriptionListRequest]) (*connect.Response[v1.SubscriptionListResponse], error) {
	return c.subscriptionList.CallUnary(ctx, req)
}

// Maintain calls event_iface.v1.EventService.Maintain.
func (c *eventServiceClient) Maintain(ctx context.Context, req *connect.Request[v1.MaintainRequest]) (*connect.ServerStreamForClient[v1.MaintainResponse], error) {
	return c.maintain.CallServerStream(ctx, req)
}

// EventServiceHandler is an implementation of the event_iface.v1.EventService service.
type EventServiceHandler interface {
	Pull(context.Context, *connect.Request[v1.PullRequest], *connect.ServerStream[v1.PullResponse]) error
	Send(context.Context, *connect.Request[v1.SendRequest]) (*connect.Response[v1.SendResponse], error)
	Ack(context.Context, *connect.Request[v1.AckRequest]) (*connect.Response[v1.AckResponse], error)
	TopicList(context.Context, *connect.Request[v1.TopicListRequest]) (*connect.Response[v1.TopicListResponse], error)
	SubscriptionList(context.Context, *connect.Request[v1.SubscriptionListRequest]) (*connect.Response[v1.SubscriptionListResponse], error)
	Maintain(context.Context, *connect.Request[v1.MaintainRequest], *connect.ServerStream[v1.MaintainResponse]) error
}

// NewEventServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEventServiceHandler(svc EventServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	eventServiceMethods := v1.File_event_iface_v1_service_proto.Services().ByName("EventService").Methods()
	eventServicePullHandler := connect.NewServerStreamHandler(
		EventServicePullProcedure,
		svc.Pull,
		connect.WithSchema(eventServiceMethods.ByName("Pull")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceSendHandler := connect.NewUnaryHandler(
		EventServiceSendProcedure,
		svc.Send,
		connect.WithSchema(eventServiceMethods.ByName("Send")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceAckHandler := connect.NewUnaryHandler(
		EventServiceAckProcedure,
		svc.Ack,
		connect.WithSchema(eventServiceMethods.ByName("Ack")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceTopicListHandler := connect.NewUnaryHandler(
		EventServiceTopicListProcedure,
		svc.TopicList,
		connect.WithSchema(eventServiceMethods.ByName("TopicList")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceSubscriptionListHandler := connect.NewUnaryHandler(
		EventServiceSubscriptionListProcedure,
		svc.SubscriptionList,
		connect.WithSchema(eventServiceMethods.ByName("SubscriptionList")),
		connect.WithHandlerOptions(opts...),
	)
	eventServiceMaintainHandler := connect.NewServerStreamHandler(
		EventServiceMaintainProcedure,
		svc.Maintain,
		connect.WithSchema(eventServiceMethods.ByName("Maintain")),
		connect.WithHandlerOptions(opts...),
	)
	return "/event_iface.v1.EventService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EventServicePullProcedure:
			eventServicePullHandler.ServeHTTP(w, r)
		case EventServiceSendProcedure:
			eventServiceSendHandler.ServeHTTP(w, r)
		case EventServiceAckProcedure:
			eventServiceAckHandler.ServeHTTP(w, r)
		case EventServiceTopicListProcedure:
			eventServiceTopicListHandler.ServeHTTP(w, r)
		case EventServiceSubscriptionListProcedure:
			eventServiceSubscriptionListHandler.ServeHTTP(w, r)
		case EventServiceMaintainProcedure:
			eventServiceMaintainHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEventServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEventServiceHandler struct{}

func (UnimplementedEventServiceHandler) Pull(context.Context, *connect.Request[v1.PullRequest], *connect.ServerStream[v1.PullResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("event_iface.v1.EventService.Pull is not implemented"))
}

func (UnimplementedEventServiceHandler) Send(context.Context, *connect.Request[v1.SendRequest]) (*connect.Response[v1.SendResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("event_iface.v1.EventService.Send is not implemented"))
}

func (UnimplementedEventServiceHandler) Ack(context.Context, *connect.Request[v1.AckRequest]) (*connect.Response[v1.AckResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("event_iface.v1.EventService.Ack is not implemented"))
}

func (UnimplementedEventServiceHandler) TopicList(context.Context, *connect.Request[v1.TopicListRequest]) (*connect.Response[v1.TopicListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("event_iface.v1.EventService.TopicList is not implemented"))
}

func (UnimplementedEventServiceHandler) SubscriptionList(context.Context, *connect.Request[v1.SubscriptionListRequest]) (*connect.Response[v1.SubscriptionListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("event_iface.v1.EventService.SubscriptionList is not implemented"))
}

func (UnimplementedEventServiceHandler) Maintain(context.Context, *connect.Request[v1.MaintainRequest], *connect.ServerStream[v1.MaintainResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("event_iface.v1.EventService.Maintain is not implemented"))
}
