// Generate everything that gets typed or pasted into the YouTube upload form.
//
//   release/youtube.md              the guide + checklist (read this one)
//   release/youtube/title.txt       one line, paste into Title
//   release/youtube/description.txt paste into Description (chapters included)
//   release/youtube/tags.txt        comma-separated, paste into Tags
//
// The plain .txt files exist because copying out of a fenced markdown block
// drags the fences along with it often enough to be worth avoiding.
//
// Chapter timestamps are NOT written by hand. They come from
// release/video/chapters.json, which the recorder stamps as it goes, because
// beat lengths drift the moment a `waitFor` takes longer than on the previous
// take. Hand-written timestamps would be wrong on the first re-record and
// nobody would notice until a viewer clicked one.
//
// Usage: node release/description.mjs

import { execFile } from "node:child_process";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

const run = promisify(execFile);
const HERE = path.dirname(fileURLToPath(import.meta.url));
const VIDEO_DIR = path.join(HERE, "video");
const OUT_DIR = path.join(HERE, "youtube");
const MP4 = path.join(VIDEO_DIR, "justmart-product-tour-1080p.mp4");

const mmss = (s) => `${Math.floor(s / 60)}:${String(s % 60).padStart(2, "0")}`;

/** Real runtime off the encoded file; the last chapter only says where it started. */
async function runtime() {
  try {
    const { stdout } = await run("ffprobe", [
      "-v", "error",
      "-show_entries", "format=duration",
      "-of", "default=nw=1:nk=1",
      MP4,
    ]);
    return mmss(Math.round(Number.parseFloat(stdout.trim())));
  } catch {
    return null;
  }
}

const chapters = JSON.parse(await readFile(path.join(VIDEO_DIR, "chapters.json"), "utf8"));
if (chapters.length < 3 || chapters[0].at !== 0) {
  throw new Error("YouTube needs at least 3 chapters and the first must be at 0:00");
}
// YouTube drops the ENTIRE chapter list if any two marks are under 10s apart,
// silently. Fail loudly here instead of discovering it after publishing.
for (let i = 1; i < chapters.length; i++) {
  const gap = chapters[i].at - chapters[i - 1].at;
  if (gap < 10) {
    throw new Error(
      `chapters "${chapters[i - 1].title}" -> "${chapters[i].title}" are ${gap}s apart; ` +
        "YouTube needs >=10s and ignores the whole list otherwise. Lengthen that " +
        "section in product-tour.spec.ts and re-record.",
    );
  }
}

const length = await runtime();
const chapterLines = chapters.map((c) => `${mmss(c.at)} ${c.title}`).join("\n");

const TITLE = "Justmart — Aplikasi Kasir & Stok untuk Toko dan Apotek";

const ALT_TITLES = [
  "Tur Lengkap Justmart: Kasir, Stok, Restok, dan Laporan",
  "Aplikasi Kasir + Manajemen Stok untuk Toko dan Apotek (Justmart)",
];

const DESCRIPTION = `Justmart menggabungkan kasir, stok, restok, dan laporan dalam satu aplikasi —
untuk toko maupun apotek.

Video ini merekam aplikasi yang benar-benar berjalan: setiap angka di layar
berasal dari transaksi yang dicatat aplikasinya sendiri, bukan mockup.

Isi video:

${chapterLines}

Beberapa hal yang terlihat di sepanjang video:

- Kasir cepat: cari barang atau scan barcode, lalu selesaikan transaksi.
- Harga grosir otomatis: tentukan "beli 12 harga sekian", kasir memakainya
  sendiri tanpa dihitung manual.
- Jual dan beli dalam satuan berbeda (pcs, dus) — stok tetap dihitung dalam
  satuan terkecil.
- Catat barang datang lengkap dengan nomor batch dan tanggal kedaluwarsa;
  modal per batch dipakai untuk menghitung profit.
- Laporan harian: terjual, HPP, dan profit, dalam bentuk tabel maupun grafik.
- Banyak gudang atau cabang, dengan stok dan laporan yang mengikuti gudang aktif.
- Mode apotek: menu Resep muncul dan kasir meminta resep untuk obat yang
  memerlukannya.

Jalan di satu komputer, tanpa langganan bulanan.

Info & unduh: LINK
Tanya-jawab: LINK
`;

const TAGS = [
  "aplikasi kasir",
  "software kasir",
  "aplikasi kasir toko",
  "aplikasi apotek",
  "software apotek",
  "manajemen stok",
  "aplikasi stok barang",
  "point of sale indonesia",
  "pos indonesia",
  "kasir offline",
  "aplikasi minimarket",
  "stok opname",
  "laporan penjualan",
  "harga grosir",
  "justmart",
].join(", ");

await mkdir(OUT_DIR, { recursive: true });
await writeFile(path.join(OUT_DIR, "title.txt"), TITLE + "\n", "utf8");
await writeFile(path.join(OUT_DIR, "description.txt"), DESCRIPTION, "utf8");
await writeFile(path.join(OUT_DIR, "tags.txt"), TAGS + "\n", "utf8");

const guide = `# YouTube upload — Justmart product tour

Generated by \`release/description.mjs\`. Re-run it after every re-record: the
timestamps below belong to one specific take.

## Files

| What | Where |
|---|---|
| Video | \`release/video/justmart-product-tour-1080p.mp4\` (1920x1080, H.264 + AAC${length ? `, ${length}` : ""}) |
| Thumbnail A | \`release/video/thumbnail-kasir.jpg\` (POS) |
| Thumbnail B | \`release/video/thumbnail-laporan.jpg\` (grafik laporan) |
| Subtitles | \`release/video/subtitles.id.srt\` (Indonesian) |
| Title | \`release/youtube/title.txt\` |
| Description | \`release/youtube/description.txt\` |
| Tags | \`release/youtube/tags.txt\` |

> **Before publishing**, settle the one claim the video makes that no recording
> can verify: the closing card and the description both say "jalan di satu
> komputer, tanpa langganan bulanan". And fill in the two \`LINK\` placeholders in
> the description — they are left blank on purpose.

## Title

\`\`\`text
${TITLE}
\`\`\`

Alternatives (all under YouTube's 100-character limit):

${ALT_TITLES.map((t, i) => `${i + 1}. ${t}`).join("\n")}

## Chapters

\`\`\`text
${chapterLines}
\`\`\`

Already embedded in the description. YouTube only renders them when the first
mark is \`0:00\`, there are at least three, and every gap is at least 10 seconds —
this script fails rather than emit a list that would be silently ignored.

## Upload checklist

1. Upload the MP4. **Visibility: Unlisted first** — watch it once end to end,
   then switch to Public.
2. Paste title, description and tags from \`release/youtube/\`.
3. Upload \`thumbnail-kasir.jpg\` (or \`thumbnail-laporan.jpg\`) as the thumbnail.
   Both are 1280x720 JPEG, well under YouTube's 2 MB ceiling.
4. **Subtitles ▸ Add ▸ Upload file ▸ With timing**, pick \`subtitles.id.srt\`,
   language **Indonesian**. The captions are already burned into the picture;
   this track is what YouTube indexes for search and what feeds auto-translate.
5. Set **video language: Indonesian** and **category: Science & Technology**.
6. Audience: **not made for kids**.
7. Leave "Allow embedding" on if the video will be linked from a landing page.

## Notes

- **No voice-over.** Narration is burned-in Indonesian captions over a generated
  music bed. If you want a voice track later, record it against this same file —
  the pacing was written to be narratable.
- **Regenerating a thumbnail:** \`node release/thumbnail.mjs\` (\`--only kasir\`).
  Frame choice, crop and copy live at the top of that script.
`;

await writeFile(path.join(HERE, "youtube.md"), guide, "utf8");

console.log(`wrote ${path.join(HERE, "youtube.md")}`);
console.log(`wrote ${OUT_DIR}/{title,description,tags}.txt`);
console.log(chapterLines);
