// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: event_iface/v1/service.proto

package event_ifacev1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AckRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Subscription string                 `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	// Opaque ack ids taken from delivered Event.ack_id. Unknown/foreign ids are
	// ignored.
	AckIds        []string `protobuf:"bytes,2,rep,name=ack_ids,json=ackIds,proto3" json:"ack_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_event_iface_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_iface_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_event_iface_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *AckRequest) GetSubscription() string {
	if x != nil {
		return x.Subscription
	}
	return ""
}

func (x *AckRequest) GetAckIds() []string {
	if x != nil {
		return x.AckIds
	}
	return nil
}

type AckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of deliveries actually acknowledged by this call.
	Acked         int64 `protobuf:"varint,1,opt,name=acked,proto3" json:"acked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_event_iface_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_iface_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_event_iface_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *AckResponse) GetAcked() int64 {
	if x != nil {
		return x.Acked
	}
	return 0
}

// Topic is a named channel messages are published to.
type Topic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_event_iface_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_event_iface_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_event_iface_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Topic) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

// Subscription is a durable consumer bound to a single topic. Each
// subscription receives its own copy of every message published to the topic
// after the subscription was created.
type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_event_iface_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_event_iface_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_event_iface_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *Subscription) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Subscription) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Subscription) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type MaintainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaintainRequest) Reset() {
	*x = MaintainRequest{}
	mi := &file_event_iface_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintainRequest) ProtoMessage() {}

func (x *MaintainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_iface_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintainRequest.ProtoReflect.Descriptor instead.
func (*MaintainRequest) Descriptor() ([]byte, []int) {
	return file_event_iface_v1_service_proto_rawDescGZIP(), []int{4}
}

type MaintainResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of acknowledged, past-retention messages reclaimed in this pass.
	Deleted       int64                  `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaintainResponse) Reset() {
	*x = MaintainResponse{}
	mi := &file_event_iface_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintainResponse) ProtoMessage() {}

func (x *MaintainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_iface_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintainResponse.ProtoReflect.Descriptor instead.
func (*MaintainResponse) Descriptor() ([]byte, []int) {
	return file_event_iface_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *MaintainResponse) GetDeleted() int64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

func (x *MaintainResponse) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type TopicListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicListRequest) Reset() {
	*x = TopicListRequest{}
	mi := &file_event_iface_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicListRequest) ProtoMessage() {}

func (x *TopicListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_iface_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicListRequest.ProtoReflect.Descriptor instead.
func (*TopicListRequest) Descriptor() ([]byte, []int) {
	return file_event_iface_v1_service_proto_rawDescGZIP(), []int{6}
}

type TopicListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*Topic               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicListResponse) Reset() {
	*x = TopicListResponse{}
	mi := &file_event_iface_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicListResponse) ProtoMessage() {}

func (x *TopicListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_iface_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicListResponse.ProtoReflect.Descriptor instead.
func (*TopicListResponse) Descriptor() ([]byte, []int) {
	return file_event_iface_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *TopicListResponse) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

type SubscriptionListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionListRequest) Reset() {
	*x = SubscriptionListRequest{}
	mi := &file_event_iface_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionListRequest) ProtoMessage() {}

func (x *SubscriptionListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_iface_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionListRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionListRequest) Descriptor() ([]byte, []int) {
	return file_event_iface_v1_service_proto_rawDescGZIP(), []int{8}
}

type SubscriptionListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionListResponse) Reset() {
	*x = SubscriptionListResponse{}
	mi := &file_event_iface_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionListResponse) ProtoMessage() {}

func (x *SubscriptionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_iface_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionListResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionListResponse) Descriptor() ([]byte, []int) {
	return file_event_iface_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *SubscriptionListResponse) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type PullRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Subscription string                 `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	// Topic to bind the subscription to when it does not yet exist. Ignored for
	// an existing subscription.
	Topic         string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_event_iface_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_iface_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_event_iface_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *PullRequest) GetSubscription() string {
	if x != nil {
		return x.Subscription
	}
	return ""
}

func (x *PullRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	PublishTime   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=publish_time,json=publishTime,proto3" json:"publish_time,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_event_iface_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_event_iface_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_event_iface_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Message) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Message) GetPublishTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishTime
	}
	return nil
}

func (x *Message) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type Event struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Subscription string                 `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	Message      *Message               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Opaque, per-delivery handle the consumer echoes back via Ack to confirm
	// receipt. Until acked (or the ack deadline lapses) the message is redelivered.
	AckId         string `protobuf:"bytes,3,opt,name=ack_id,json=ackId,proto3" json:"ack_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_iface_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_iface_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_iface_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *Event) GetSubscription() string {
	if x != nil {
		return x.Subscription
	}
	return ""
}

func (x *Event) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Event) GetAckId() string {
	if x != nil {
		return x.AckId
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_event_iface_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_event_iface_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_event_iface_v1_service_proto_rawDescGZIP(), []int{13}
}

type PullResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to D:
	//
	//	*PullResponse_Ping
	//	*PullResponse_Event
	D             isPullResponse_D `protobuf_oneof:"d"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullResponse) Reset() {
	*x = PullResponse{}
	mi := &file_event_iface_v1_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullResponse) ProtoMessage() {}

func (x *PullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_iface_v1_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullResponse.ProtoReflect.Descriptor instead.
func (*PullResponse) Descriptor() ([]byte, []int) {
	return file_event_iface_v1_service_proto_rawDescGZIP(), []int{14}
}

func (x *PullResponse) GetD() isPullResponse_D {
	if x != nil {
		return x.D
	}
	return nil
}

func (x *PullResponse) GetPing() *Ping {
	if x != nil {
		if x, ok := x.D.(*PullResponse_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *PullResponse) GetEvent() *Event {
	if x != nil {
		if x, ok := x.D.(*PullResponse_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isPullResponse_D interface {
	isPullResponse_D()
}

type PullResponse_Ping struct {
	Ping *Ping `protobuf:"bytes,1,opt,name=ping,proto3,oneof"`
}

type PullResponse_Event struct {
	Event *Event `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

func (*PullResponse_Ping) isPullResponse_D() {}

func (*PullResponse_Event) isPullResponse_D() {}

type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Message       *Message               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_event_iface_v1_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_iface_v1_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_event_iface_v1_service_proto_rawDescGZIP(), []int{15}
}

func (x *SendRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SendRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type SendResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-assigned id of the published message (echoes message.message_id when
	// the caller supplied one).
	MessageId     string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_event_iface_v1_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_iface_v1_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_event_iface_v1_service_proto_rawDescGZIP(), []int{16}
}

func (x *SendResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

var File_event_iface_v1_service_proto protoreflect.FileDescriptor

const file_event_iface_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1cevent_iface/v1/service.proto\x12\x0eevent_iface.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\\\n" +
	"\n" +
	"AckRequest\x12+\n" +
	"\fsubscription\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\fsubscription\x12!\n" +
	"\aack_ids\x18\x02 \x03(\tB\b\xbaH\x05\x92\x01\x02\b\x01R\x06ackIds\"#\n" +
	"\vAckResponse\x12\x14\n" +
	"\x05acked\x18\x01 \x01(\x03R\x05acked\"X\n" +
	"\x05Topic\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\vcreate_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\"u\n" +
	"\fSubscription\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12;\n" +
	"\vcreate_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\"\x11\n" +
	"\x0fMaintainRequest\"\\\n" +
	"\x10MaintainResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\x03R\adeleted\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"\x12\n" +
	"\x10TopicListRequest\"B\n" +
	"\x11TopicListResponse\x12-\n" +
	"\x06topics\x18\x01 \x03(\v2\x15.event_iface.v1.TopicR\x06topics\"\x19\n" +
	"\x17SubscriptionListRequest\"^\n" +
	"\x18SubscriptionListResponse\x12B\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x1c.event_iface.v1.SubscriptionR\rsubscriptions\"P\n" +
	"\vPullRequest\x12+\n" +
	"\fsubscription\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\fsubscription\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\"\x83\x02\n" +
	"\aMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12=\n" +
	"\fpublish_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vpublishTime\x12G\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2'.event_iface.v1.Message.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"u\n" +
	"\x05Event\x12\"\n" +
	"\fsubscription\x18\x01 \x01(\tR\fsubscription\x121\n" +
	"\amessage\x18\x02 \x01(\v2\x17.event_iface.v1.MessageR\amessage\x12\x15\n" +
	"\x06ack_id\x18\x03 \x01(\tR\x05ackId\"\x06\n" +
	"\x04Ping\"n\n" +
	"\fPullResponse\x12*\n" +
	"\x04ping\x18\x01 \x01(\v2\x14.event_iface.v1.PingH\x00R\x04ping\x12-\n" +
	"\x05event\x18\x02 \x01(\v2\x15.event_iface.v1.EventH\x00R\x05eventB\x03\n" +
	"\x01d\"g\n" +
	"\vSendRequest\x12\x1d\n" +
	"\x05topic\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05topic\x129\n" +
	"\amessage\x18\x02 \x01(\v2\x17.event_iface.v1.MessageB\x06\xbaH\x03\xc8\x01\x01R\amessage\"-\n" +
	"\fSendResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId2\xe0\x03\n" +
	"\fEventService\x12C\n" +
	"\x04Pull\x12\x1b.event_iface.v1.PullRequest\x1a\x1c.event_iface.v1.PullResponse0\x01\x12A\n" +
	"\x04Send\x12\x1b.event_iface.v1.SendRequest\x1a\x1c.event_iface.v1.SendResponse\x12>\n" +
	"\x03Ack\x12\x1a.event_iface.v1.AckRequest\x1a\x1b.event_iface.v1.AckResponse\x12P\n" +
	"\tTopicList\x12 .event_iface.v1.TopicListRequest\x1a!.event_iface.v1.TopicListResponse\x12e\n" +
	"\x10SubscriptionList\x12'.event_iface.v1.SubscriptionListRequest\x1a(.event_iface.v1.SubscriptionListResponse\x12O\n" +
	"\bMaintain\x12\x1f.event_iface.v1.MaintainRequest\x1a .event_iface.v1.MaintainResponse0\x01BRZPgithub.com/wargasipil/warga_collections/definitions/event_iface/v1;event_ifacev1b\x06proto3"

var (
	file_event_iface_v1_service_proto_rawDescOnce sync.Once
	file_event_iface_v1_service_proto_rawDescData []byte
)

func file_event_iface_v1_service_proto_rawDescGZIP() []byte {
	file_event_iface_v1_service_proto_rawDescOnce.Do(func() {
		file_event_iface_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_iface_v1_service_proto_rawDesc), len(file_event_iface_v1_service_proto_rawDesc)))
	})
	return file_event_iface_v1_service_proto_rawDescData
}

var file_event_iface_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_event_iface_v1_service_proto_goTypes = []any{
	(*AckRequest)(nil),               // 0: event_iface.v1.AckRequest
	(*AckResponse)(nil),              // 1: event_iface.v1.AckResponse
	(*Topic)(nil),                    // 2: event_iface.v1.Topic
	(*Subscription)(nil),             // 3: event_iface.v1.Subscription
	(*MaintainRequest)(nil),          // 4: event_iface.v1.MaintainRequest
	(*MaintainResponse)(nil),         // 5: event_iface.v1.MaintainResponse
	(*TopicListRequest)(nil),         // 6: event_iface.v1.TopicListRequest
	(*TopicListResponse)(nil),        // 7: event_iface.v1.TopicListResponse
	(*SubscriptionListRequest)(nil),  // 8: event_iface.v1.SubscriptionListRequest
	(*SubscriptionListResponse)(nil), // 9: event_iface.v1.SubscriptionListResponse
	(*PullRequest)(nil),              // 10: event_iface.v1.PullRequest
	(*Message)(nil),                  // 11: event_iface.v1.Message
	(*Event)(nil),                    // 12: event_iface.v1.Event
	(*Ping)(nil),                     // 13: event_iface.v1.Ping
	(*PullResponse)(nil),             // 14: event_iface.v1.PullResponse
	(*SendRequest)(nil),              // 15: event_iface.v1.SendRequest
	(*SendResponse)(nil),             // 16: event_iface.v1.SendResponse
	nil,                              // 17: event_iface.v1.Message.AttributesEntry
	(*timestamppb.Timestamp)(nil),    // 18: google.protobuf.Timestamp
}
var file_event_iface_v1_service_proto_depIdxs = []int32{
	18, // 0: event_iface.v1.Topic.create_time:type_name -> google.protobuf.Timestamp
	18, // 1: event_iface.v1.Subscription.create_time:type_name -> google.protobuf.Timestamp
	18, // 2: event_iface.v1.MaintainResponse.time:type_name -> google.protobuf.Timestamp
	2,  // 3: event_iface.v1.TopicListResponse.topics:type_name -> event_iface.v1.Topic
	3,  // 4: event_iface.v1.SubscriptionListResponse.subscriptions:type_name -> event_iface.v1.Subscription
	18, // 5: event_iface.v1.Message.publish_time:type_name -> google.protobuf.Timestamp
	17, // 6: event_iface.v1.Message.attributes:type_name -> event_iface.v1.Message.AttributesEntry
	11, // 7: event_iface.v1.Event.message:type_name -> event_iface.v1.Message
	13, // 8: event_iface.v1.PullResponse.ping:type_name -> event_iface.v1.Ping
	12, // 9: event_iface.v1.PullResponse.event:type_name -> event_iface.v1.Event
	11, // 10: event_iface.v1.SendRequest.message:type_name -> event_iface.v1.Message
	10, // 11: event_iface.v1.EventService.Pull:input_type -> event_iface.v1.PullRequest
	15, // 12: event_iface.v1.EventService.Send:input_type -> event_iface.v1.SendRequest
	0,  // 13: event_iface.v1.EventService.Ack:input_type -> event_iface.v1.AckRequest
	6,  // 14: event_iface.v1.EventService.TopicList:input_type -> event_iface.v1.TopicListRequest
	8,  // 15: event_iface.v1.EventService.SubscriptionList:input_type -> event_iface.v1.SubscriptionListRequest
	4,  // 16: event_iface.v1.EventService.Maintain:input_type -> event_iface.v1.MaintainRequest
	14, // 17: event_iface.v1.EventService.Pull:output_type -> event_iface.v1.PullResponse
	16, // 18: event_iface.v1.EventService.Send:output_type -> event_iface.v1.SendResponse
	1,  // 19: event_iface.v1.EventService.Ack:output_type -> event_iface.v1.AckResponse
	7,  // 20: event_iface.v1.EventService.TopicList:output_type -> event_iface.v1.TopicListResponse
	9,  // 21: event_iface.v1.EventService.SubscriptionList:output_type -> event_iface.v1.SubscriptionListResponse
	5,  // 22: event_iface.v1.EventService.Maintain:output_type -> event_iface.v1.MaintainResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_event_iface_v1_service_proto_init() }
func file_event_iface_v1_service_proto_init() {
	if File_event_iface_v1_service_proto != nil {
		return
	}
	file_event_iface_v1_service_proto_msgTypes[14].OneofWrappers = []any{
		(*PullResponse_Ping)(nil),
		(*PullResponse_Event)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_iface_v1_service_proto_rawDesc), len(file_event_iface_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_iface_v1_service_proto_goTypes,
		DependencyIndexes: file_event_iface_v1_service_proto_depIdxs,
		MessageInfos:      file_event_iface_v1_service_proto_msgTypes,
	}.Build()
	File_event_iface_v1_service_proto = out.File
	file_event_iface_v1_service_proto_goTypes = nil
	file_event_iface_v1_service_proto_depIdxs = nil
}
